name: CI

permissions: read-all

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install system OCaml
        run: |
          sudo apt-get update
          sudo apt-get install -y ocaml
      - name: Set up opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14.x"
          dune-cache: true
          opam-disable-sandboxing: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            iris-dev: https://gitlab.mpi-sws.org/iris/opam.git
      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: "_opam"
          key: opam-${{ runner.os }}-${{ hashFiles('*.opam.locked') }}
      - name: Build opam dependencies
        run: |
          opam install . --deps-only --locked
      - name: Rocq build
        run: |
          eval $(opam env)
          make
